name: Run Streamlit Logging Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (if needed)
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python publish_web.py

      - name: Commit and push updated log
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Use the token to authenticate with GitHub
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${REPO}.git

          git pull origin main --no-rebase  # avoid rebase conflicts in CI

          git add execution_log.txt

          if git diff --cached --quiet; then
            echo " No changes to commit."
          else
            git commit -m "Update execution log [auto]"
            git push origin main
          fi

